# Generated by Django 5.2.5 on 2025-09-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0002_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='colors',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
